#define OP_LOAD_CONSTANT_gI				0x00
#define OP_LOAD_GLOBAL_gI				0x01
#define OP_STORE_GLOBAL_gI				0x02
#define OP_LOAD_LOCAL_gI				0x03
#define OP_STORE_LOCAL_gI				0x04
#define OP_CALL_gSignature_gArity		0x05
#define OP_JUMP_2offset					0x06
#define OP_LOOP_2offset					0x07
#define OP_JUMP_IF_TRUE_2offset			0x08
#define OP_JUMP_IF_FALSE_2offset		0x09
#define OP_DISCARD_gCount				0x0A
#define OP_IMPORT						0x0B
#define OP_MAKE_NEW_CLASS				0x0C
#define OP_ADD_METHOD					0x0D
#define OP_ADD_FOREIGN_METHOD			0x0E
#define OP_TYPEOF						0x0F
#define OP_BIND_SUPERCLASS				0x10
#define OP_RETURN						0x11
#define OP_LOAD_NULL					0x12
#define OP_DISCARD						0x13
